### ISSUE TITLE
FetchError with candles service

### ISSUE THREAD

**Issue by ThomasTL** [Ashlar/binance-api-node#254]
Not sure what am i doing wrong.
I had this exception quite a number of time calling `candles` service.
```
FetchError: request to https://api.binance.com/api/v1/klines?interval=5m&symbol=XMRBTC&limit=4 failed, reason: getaddrinfo ENOTFOUND api.binance.com
    at ClientRequest.<anonymous> (/Users/thomas/Documents/Perso/Dev/Node/gorilla-signals/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}
```

**Comment by balthazar** [comment]
That's a problem on your side, looks like your connection is getting interrupted / unstable
