### ISSUE TITLE
symbol.toLowerCase not being caught on websockets

### ISSUE THREAD

**Issue by digimbyte** [Ashlar/binance-api-node#374]
looks like if a false symbol request comes through and it's not caught, it won't throw an error
```
D:\development\Binancer\node_modules\binance-api-node\dist\websocket.js:455
    var w = (0, _openWebsocket.default)("".concat(endpoints.base, "/").concat(symbol.toLowerCase(), "@trade"));
                                                                                     ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at D:\development\Binancer\node_modules\binance-api-node\dist\websocket.js:455:86
    at Array.map (<anonymous>)
    at Object.trades (D:\development\Binancer\node_modules\binance-api-node\dist\websocket.js:454:62)
    at startListeners (file:///D:/development/Binancer/app.js:755:37)
    at file:///D:/development/Binancer/app.js:400:9
    at ReconnectingWebSocket.w.onmessage (D:\development\Binancer\node_modules\binance-api-node\dist\websocket.js:316:5)
    at afterWrite (node:internal/streams/writable:503:5)
```

**Comment by balthazar** [comment]
Shouldn't you be checking for that regardless? I don't think we would do anything else than throw anyway if a null symbol is provided

**Comment by digimbyte** [comment]
yes, but a throw is not present on the current version.
it's a minor bug to put on the todo list of 'polishing'
