### ISSUE TITLE
dailyStats is not a function

### ISSUE THREAD

**Issue by ThallyssonKlein** [Ashlar/binance-api-node#423]
I'm trying to run this:

```
const generalBinance = new Binance().options({
        APIKEY: "mykey",
        APISECRET: "mysecret"
});
console.log(await generalBinance.dailyStats({ symbol: 'ETHBTC' }))
```

The result:

```
(node:28) UnhandledPromiseRejectionWarning: TypeError: generalBinance.dailyStats is not a function
    at /src/index.js:128:38
    at Object.<anonymous> (/src/index.js:129:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by balthazar** [comment]
wrong package.
